name: nawy_task
description: "Nawy Senior Position Assessment"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #State Management
  provider: ^6.1.2

  #Network Service
  dio: ^5.8.0+1
  dio_request_inspector: ^3.2.0

  #JSON
  json_annotation: ^4.9.0

  #Images Utils
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.0

  #UI Components
  shimmer: ^3.0.0
  fluttertoast: ^8.2.10
  modal_bottom_sheet: ^3.0.0

  #Routing
  go_router: ^15.1.2

  #Screens Utils
  flutter_screenutil: ^5.9.3

  #Local Storage
  flutter_secure_storage: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  generate: false
  assets:
    - res/images/
    - res/images/icons/